# Generated by Django 5.1.6 on 2025-02-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='chanel_icon/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='chanel_banner/')),
                ('description', models.TextField()),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_chanels', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chanel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chanel',
                'verbose_name_plural': 'Chanels',
            },
        ),
    ]
