# Generated by Django 5.1.6 on 2025-02-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_chanel_user'),
        ('content', '0002_alter_video_author_alter_video_description_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to='accounts.chanel'),
        ),
    ]
