# Generated by Django 5.1.1 on 2025-02-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_commentlike_user_alter_commentreply_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='author',
            new_name='user',
        ),
    ]
