# Generated by Django 5.1.1 on 2025-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_author_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos_playlists', to='content.video'),
        ),
    ]
